---
all:
  #hosts:
  #  pihole01:
  #  pihole02:
  children:
    rpi:
      hosts:
        pihole02:
    ubuntu:
      hosts:
        pihole01:
        pihole02:
    pihole:
      hosts:
        #pihole01:
        pihole02:
