---
all:
  hosts:
    dns01:
    dns02:
  children:
    rpi:
      hosts:
        dns02:
    ubuntu:
      hosts:
        dns01:
        dns02:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    pihole:
      hosts:
        #dns01:
        dns02:
    powerdns:
      hosts:
        #dns01:
        dns02:
