---
all:
  #hosts:
  #  pihole01:
  #  pihole02:
  children:
    rpi:
      hosts:
        pihole02:
    ubuntu:
      hosts:
        pihole01:
        pihole02:
      vars:
        ansible_python_interpreter: /usr/bin/python3
    pihole:
      hosts:
        #pihole01:
        pihole02:
    powerdns:
      hosts:
        #pihole01:
        pihole02:
