- hosts: rpi
  become: true
  tasks:
  - import_role:
      name: rpi
    tags: [rpi]

- hosts: all
  become: true
  tasks:
  - import_role:
      name: base
    vars:
      user_ssh_authorized_keys: "{{ my_ssh_authorized_keys }}"
    tags: [base]

- hosts: pihole
  become: true
  tasks:
  - import_role:
      name: pihole
    tags: [pihole]
