- name: Docker | install prerequisite packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python3-pip

- name: Docker install pip packages
  pip:
    name: docker-py
    state: latest

- name: Docker | add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker | add repository
  apt_repository:
    repo: deb [arch={{ apt_arch[ansible_machine] }}] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
    update_cache: yes

- name: Docker | install docker
  apt:
    name: "{{ item }}"
    state: latest
  loop:
  - docker-ce
  - docker-ce-cli
  - containerd.io
