- name: Users - add my user
  user:
    name: "{{ user_username }}"
    password: "{{ user_password | password_hash('sha512', inventory_hostname | hash('sha1') | truncate(16)) }}"
    groups: "{{ user_groups }}"
    append: true
    shell: /bin/bash
    skeleton: /etc/skel
    state: present

- name: Users - add the authorized SSH keys
  authorized_key:
    user: "{{ user_username }}"
    key: "{{ item }}"
    state: present
  loop: "{{ user_ssh_authorized_keys }}"

- name: Users - remove default user
  user:
    name: "{{ user_default }}"
    remove: yes
    state: absent