pihole_config_base_path: /opt/pihole
pihole_config_path: "{{ pihole_config_base_path }}/etc-pihole"
pihole_admin_servername: pihole.example.com
pihole_network_interface: eth0
pihole_ipv4_address: 127.0.0.1/24
pihole_ipv6_address: ::1
pihole_upstream_dns:
- "9.9.9.9"
- "2620:fe::fe"
dnsmasq_overrides: []
dnsmasq_config_path: "{{ pihole_config_base_path }}/etc-dnsmasq.d"
nginx_config_path: "{{ pihole_config_base_path }}/etc-nginx"
nginx_config_mounts: []