- name: Install | download Pi-Hole installer
  get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: 0740

- name: Install | create Pi-Hole configuration directory
  file:
    name: "{{ pihole_config_path }}"
    state: directory
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0755

- name: Install | create Pi-Hole configuration file
  template:
    src: "setupVars.conf.j2"
    dest: "{{ pihole_config_path }}/setupVars.conf"
    owner: root
    group: root
    mode: 0644

- name: Install | install Pi-Hole
  shell: "~/install-pihole.sh --unattended"
  register: install_pihole

- name: Install | set Pi-Hole to update every week
  replace:
    path: /etc/cron.d/pihole
    regexp: '^#(.*updatePihole.*)$'
    replace: '\1'
    backup: yes