- name: resolv.conf | disconnect from systemd-resolved
  file:
    src: /run/resolvconf/resolv.conf
    dest: /etc/resolv.conf
    state: link

- name: resolv.conf | set local resolver
  file: 
    path: /etc/resolvconf/resolv.conf.d/base
    content: |
      nameserver 127.0.0.1
  register: resolvconf

- name: resolv.conf | update
  shell: resolvconf --enable-updates && resolvconf -u
  when: resolvconf.changed

- name: systemd-resolved | stop and disable stub resolver
  service: 
    name: systemd-resolved
    enabled: no
    state: stopped
